print("learning to move the file object")
fileobject = open("short.txt", "r+")
File = fileobject.read()
print(File)
print("Initially, the position of the file object : ", fileobject.tell(), "\n\n")
fileobject.seek(0)
print("Now the file object is at the beggining of the file :", fileobject.tell(), "\n\n")
fileobject.seek(5)
print("We are moving to the 10th byte position from the beginning of file", "\n\n")
print("the position of the file object is at ", fileobject.tell())
print(File)